### ISSUE TITLE
ERR_CONNECTION_REFUSED New Install

### ISSUE THREAD

**Issue by davidjmorin** [ibracorp/authelia#15]
I have followed this to the T and am unable to access it via IP or URL.  

```
This site can’t be reached192.168.1.17 refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
```

```
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

## The host and port to listen on.
host: 0.0.0.0
port: 8443

theme: light

server:
  read_buffer_size: 4096
  write_buffer_size: 4096
  path: ""

jwt_secret: ShVmYq3t6w9z$C&F

default_redirection_url: https://home.example.com:8080/

totp:
  skew: 1

authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m

  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8
      
access_control:

  rules:

    - domain: "*.MYWEBSITE.io"
      subject:
        - "group:admins"
        - "group:moderators"
      policy: one_factor
      
session:
  name: authelia_session
  secret: ShVmYq3t6w9z$C&F  
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M

  domain: MYWEBSITE.io

  redis:
    host: 192.168.1.17
    port: 6379
    # username: authelia
    password: MYPASS04!
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  mysql:
    host: 192.168.1.17
    port: 3306
    database: authelia
    username: root
    password: MYPASS04!

notifier:
  filesystem:
   filename: /config/notification.txt

...
```
