### ISSUE TITLE
Buffer size error

### ISSUE THREAD

**Issue by thatnovaguy** [ibracorp/authelia#19]
I'm unable to access the authelia webui and am getting a buffer size error. Do I need to change my config to what's suggested earlier in the log?
```
time="2022-09-05T10:51:13-04:00" level=warning msg="Configuration: configuration key 'server.write_buffer_size' is deprecated in 4.36.0 and has been replaced by 'server.buffers.write': this has been automatically mapped for you but you will need to adjust your configuration to remove this message"
time="2022-09-05T10:51:13-04:00" level=warning msg="Configuration: configuration key 'server.read_buffer_size' is deprecated in 4.36.0 and has been replaced by 'server.buffers.read': this has been automatically mapped for you but you will need to adjust your configuration to remove this message"
time="2022-09-05T10:51:13-04:00" level=warning msg="Configuration: access control: no rules have been specified so the 'default_policy' of 'one_factor' is going to be applied to all requests"
time="2022-09-05T10:51:13-04:00" level=info msg="Authelia v4.36.6 is starting"
time="2022-09-05T10:51:13-04:00" level=info msg="Log severity set to info"
time="2022-09-05T10:51:13-04:00" level=info msg="Storage schema is being checked for updates"
time="2022-09-05T10:51:13-04:00" level=info msg="Storage schema is already up to date"
time="2022-09-05T10:51:13-04:00" level=info msg="Initializing server for non-TLS connections on '[::]:9091' path '/'"
time="2022-09-05T10:52:00-04:00" level=error msg="Request from client exceeded the server buffer sizes." error="error when reading request headers: small read buffer. Increase ReadBufferSize. Buffer size=4096, contents: \"GET / HTTP/1.1\\r\\nHost: 192.168.1.186:19091\\r\\nConnection: keep-alive\\r\\nUpgrade-Insecure-Requests: 1\\r\\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105\"...\"c-xVfHM0iKtCYLqSjUC1aD_VWaikFlkgh3mR1RYG1P4QyjROpZrJJGYQiCcmbJo-vxkyPYzNbbHkHkT6t4u-iYFnmoCgnlzm77gRSDnRXl2kGzmw4QqjhW-4gpukdAD3xz9LSbP7yckz8KR5kmoCynzOggp7PcmWN-x3s0YP224YUu3lH_TdOzMjk_1HDB1kVeO9J410\"" method=GET path=/ remote_ip=192.168.1.224 stack="github.com/authelia/authelia/v4/internal/server/handlers.go:72 handleError.func2\ngithub.com/valyala/fasthttp@v1.39.0/server.go:2794             (*Server).writeErrorResponse\ngithub.com/valyala/fasthttp@v1.39.0/server.go:2233             (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.39.0/workerpool.go:224          (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.39.0/workerpool.go:196          (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                       goexit" status_code=431
```
Edit: Simply increasing the buffer size did help with accessing the webui. However, I would still like to know whether the server.buffers.write change is needed.

**Comment by ArtLion74** [comment]
Just change configuration.yml from 
```
server:
  host: 0.0.0.0
  port: 9091
  path: ""
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""
```
into 

```
server:
  host: 0.0.0.0
  port: 9091
  path: ""
  buffers:
    read: 4096
    write: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""
```
